#+TITLE: Merlin backend for eldoc

This package provide a merlin backend for eldoc. Its goal is to
automatically (without using keybindings) display the type,
documentation and occurrences of the value under the point in OCaml or
ReasonML files. The information are obtained from merlin.

* Installation

For now the package is not published on melpa.

** Quelpa

With quelpa already installed and configured:

#+BEGIN_SRC emacs-lisp
(quelpa '(merlin-eldoc :repo "Khady/merlin-eldoc" :fetcher github))
#+END_SRC

** With ~use-package~

1. Clone this repository in ~$HOME/.emacs.d/vendor~

   #+BEGIN_SRC bash
mkdir -p "$HOME/.emacs.d/vendor"
cd "$HOME/.emacs.d/vendor"
git clone https://github.com/Khady/merlin-eldoc.git
   #+END_SRC

2. Add this code to ~init.el~

   #+BEGIN_SRC emacs-lisp
(use-package merlin-eldoc
  :load-path "~/.emacs.d/vendor/merlin-eldoc/"
  :hook ((reason-mode tuareg-mode caml-mode) . merlin-eldoc-setup))
   #+END_SRC

** The more manual way

1. Clone this repository in ~$HOME/.emacs.d/vendor~

   #+BEGIN_SRC bash
mkdir -p "$HOME/.emacs.d/vendor"
cd "$HOME/.emacs.d/vendor"
git clone https://github.com/Khady/merlin-eldoc.git
   #+END_SRC

2. Add this code to ~init.el~

   #+BEGIN_SRC emacs-lisp
;; Add the folder containing this package to the load-path
(add-to-list 'load-path "~/.emacs.d/vendor/merlin-eldoc/")
;; Require the package
(require 'merlin-eldoc)
;; Add a hook to start the mode automatically for OCaml and Reason
(add-hook 'tuareg-mode-hook 'merlin-eldoc-setup)
(add-hook 'reason-mode-hook 'merlin-eldoc-setup)
   #+END_SRC

* Usage

If a hook has been configured, then there is nothing to do. The eldoc
mode should be launched automatically when an OCaml file is
visited. And merlin will provide type information when available.

Otherwise, it can be launched by executing ~M-x merlin-eldoc-setup~.

Once this is done, as soon as the point is on a word which is not a
keyword, a type should be displayed in the echo area when the cursor
doesn't move for some time.

* Demo

#+ATTR_HTML: title="demo video"
[[https://d.khady.info/merlin-auto-hl.ogv][file:merlin-auto-hl.gif]]

Note that merlin is never called explicitly in this video.
